name: ESP32 Build

on:
  workflow_dispatch:   # <-- ini buat tombol manual
  push:
    branches: [ "dev-2.0" ]
  pull_request:
    branches: [ "dev-2.0" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PlatformIO
        run: |
          pip install -U platformio

      - name: Build firmware
        run: |
          pio run

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/*/firmware.bin
